configName: SAMD21_IOT_WG
folderName: SAM-IoT_SPI-Slave
format_version: v1.0
frameworkPath: ../../Harmony3
processor: ATSAMD21G18A
projectName: SAM-IoT_SPI-Slave
settings:
  PackageFilter: crypto;net;core;bsp;quick_docs;usb;wireless;bt;cryptoauthlib;csp;gfx;aws_cloud;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: ./dev_packs/arm/CMSIS/5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/SAMD21_DFP/3.4.104/samd21a/atdf/ATSAMD21G18A.atdf
