files:
- generatedChecksum: 9762B12622FD08815784244AF2080753
  logicalPath: config/SAMD21_WG_IOT
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9762B12622FD08815784244AF2080753
- generatedChecksum: 8D567C09CD87F07B0DC90BB059222337
  logicalPath: config/SAMD21_WG_IOT
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8D567C09CD87F07B0DC90BB059222337
- generatedChecksum: 1ECDD5BF527B4BBF3814948BF66AEBD6
  logicalPath: config/SAMD21_WG_IOT
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1ECDD5BF527B4BBF3814948BF66AEBD6
- generatedChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
  logicalPath: config/SAMD21_WG_IOT
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 328F1E09E0DD9BEE901C4562A3E5180A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: F2F6E18F9F573A8259272D37D74A0FC5
  logicalPath: config/SAMD21_WG_IOT/peripheral/clock
  name: plib_clock.c
  physicalPath: peripheral/clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: F2F6E18F9F573A8259272D37D74A0FC5
- generatedChecksum: 95EA211BA565655D13623C406412CBB5
  logicalPath: config/SAMD21_WG_IOT/peripheral/eic
  name: plib_eic.c
  physicalPath: peripheral/eic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 95EA211BA565655D13623C406412CBB5
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config/SAMD21_WG_IOT/peripheral/evsys
  name: plib_evsys.c
  physicalPath: peripheral/evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: 6147FAA8D1968765A60F6CBA5138E6D3
  logicalPath: config/SAMD21_WG_IOT/peripheral/nvic
  name: plib_nvic.c
  physicalPath: peripheral/nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6147FAA8D1968765A60F6CBA5138E6D3
- generatedChecksum: 12BB5180FB5A5EF3F5A1310030E4E6C5
  logicalPath: config/SAMD21_WG_IOT/peripheral/nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral/nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: 12BB5180FB5A5EF3F5A1310030E4E6C5
- generatedChecksum: 75A037187BCD5584A923599F83E61B0A
  logicalPath: config/SAMD21_WG_IOT/peripheral/port
  name: plib_port.c
  physicalPath: peripheral/port
  security: NON_SECURE
  type: SOURCE
  userChecksum: 75A037187BCD5584A923599F83E61B0A
- generatedChecksum: 34690275A1F2E01D66BA736C50BBBDE2
  logicalPath: config/SAMD21_WG_IOT/peripheral/rtc
  name: plib_rtc_timer.c
  physicalPath: peripheral/rtc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 34690275A1F2E01D66BA736C50BBBDE2
- generatedChecksum: 3A36485A72769FD607F877A2E647A3B1
  logicalPath: config/SAMD21_WG_IOT/peripheral/sercom/spi_master
  name: plib_sercom0_spi_master.c
  physicalPath: peripheral/sercom/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3A36485A72769FD607F877A2E647A3B1
- generatedChecksum: 949BBD944EC8B81E639121B72E7C7510
  logicalPath: config/SAMD21_WG_IOT
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 949BBD944EC8B81E639121B72E7C7510
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config/SAMD21_WG_IOT/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: E83A2568EB70A3E393A9421C4CEDDDD5
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: ac.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: E83A2568EB70A3E393A9421C4CEDDDD5
- generatedChecksum: 590A4F4CE794B1EB4CDE657634C91913
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: adc.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 590A4F4CE794B1EB4CDE657634C91913
- generatedChecksum: 3721B1E6D4F7F77152CF9BD8683D6B91
  logicalPath: packs/ATSAMD21G18A_DFP
  name: atsamd21g18a.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 3721B1E6D4F7F77152CF9BD8683D6B91
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cachel1_armv7.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cmsis_armcc.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cmsis_armclang.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cmsis_armclang_ltm.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cmsis_compiler.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cmsis_gcc.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cmsis_iccarm.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: cmsis_version.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: core_cm0plus.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: 016B5B4A71E106E734B16CA1517FF382
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: dac.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 016B5B4A71E106E734B16CA1517FF382
- generatedChecksum: 5948AE7EB03727780A40720ED9E95E24
  logicalPath: config/SAMD21_WG_IOT
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5948AE7EB03727780A40720ED9E95E24
- generatedChecksum: C0DDB9E7E3888CE027C282388A2F2D8E
  logicalPath: config/SAMD21_WG_IOT
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: C0DDB9E7E3888CE027C282388A2F2D8E
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config/SAMD21_WG_IOT
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: C2E075A57123D0F17F6743EB79FB5708
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: dmac.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: C2E075A57123D0F17F6743EB79FB5708
- generatedChecksum: 817445C5CD46BF44AEA791F24FFCFD9B
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: dsu.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 817445C5CD46BF44AEA791F24FFCFD9B
- generatedChecksum: D354D94F76074F550A3D39339988740E
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: eic.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: D354D94F76074F550A3D39339988740E
- generatedChecksum: CCEBBAD0032227AD71BE82D0A235ADD8
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: evsys.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: CCEBBAD0032227AD71BE82D0A235ADD8
- generatedChecksum: 1F81BE55AB45CB807013941A75AA1A57
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: gclk.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1F81BE55AB45CB807013941A75AA1A57
- generatedChecksum: 56D435F7656CC2343B84F1E66D164D64
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: hmatrixb.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 56D435F7656CC2343B84F1E66D164D64
- generatedChecksum: 998DBA248933E5682F2276B60B8FD8D8
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: i2s.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 998DBA248933E5682F2276B60B8FD8D8
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs/CMSIS/CMSIS/Core/Include
  name: mpu_armv7.h
  physicalPath: ../../packs/CMSIS/CMSIS/Core/Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: F37178E00FC83646B507901642A0100D
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: mtb.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: F37178E00FC83646B507901642A0100D
- generatedChecksum: 7296DA017FF9C40DCC08191D6999B77B
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: nvmctrl.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7296DA017FF9C40DCC08191D6999B77B
- generatedChecksum: D5A9C90744DEFF4CCDD467B77B6406CB
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: pac.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: D5A9C90744DEFF4CCDD467B77B6406CB
- generatedChecksum: C591D09F115E12D00921D14939E3900D
  logicalPath: config/SAMD21_WG_IOT/peripheral/clock
  name: plib_clock.h
  physicalPath: peripheral/clock
  security: NON_SECURE
  type: HEADER
  userChecksum: C591D09F115E12D00921D14939E3900D
- generatedChecksum: 2237C40C2227EA80BD80E81505042FEC
  logicalPath: config/SAMD21_WG_IOT/peripheral/eic
  name: plib_eic.h
  physicalPath: peripheral/eic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2237C40C2227EA80BD80E81505042FEC
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config/SAMD21_WG_IOT/peripheral/evsys
  name: plib_evsys.h
  physicalPath: peripheral/evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
  logicalPath: config/SAMD21_WG_IOT/peripheral/nvic
  name: plib_nvic.h
  physicalPath: peripheral/nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: E95AB23B866AA0CE6F0ABF637E9E2C83
- generatedChecksum: 71D16914F1E580B0AF77141622DCD865
  logicalPath: config/SAMD21_WG_IOT/peripheral/nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral/nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 71D16914F1E580B0AF77141622DCD865
- generatedChecksum: 82E58805D179EE737D84E459B68C7F1A
  logicalPath: config/SAMD21_WG_IOT/peripheral/port
  name: plib_port.h
  physicalPath: peripheral/port
  security: NON_SECURE
  type: HEADER
  userChecksum: 82E58805D179EE737D84E459B68C7F1A
- generatedChecksum: 38FC765E3F9AFC2FE0B5D95393E0E836
  logicalPath: config/SAMD21_WG_IOT/peripheral/rtc
  name: plib_rtc.h
  physicalPath: peripheral/rtc
  security: NON_SECURE
  type: HEADER
  userChecksum: 38FC765E3F9AFC2FE0B5D95393E0E836
- generatedChecksum: A8D053706578740E85A7F8342AFDDEFD
  logicalPath: config/SAMD21_WG_IOT/peripheral/sercom/spi_master
  name: plib_sercom0_spi_master.h
  physicalPath: peripheral/sercom/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A8D053706578740E85A7F8342AFDDEFD
- generatedChecksum: A06CFE6AEC7B18A5C3DEAC185207002C
  logicalPath: config/SAMD21_WG_IOT/peripheral/sercom/spi_master
  name: plib_sercom_spi_master_common.h
  physicalPath: peripheral/sercom/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A06CFE6AEC7B18A5C3DEAC185207002C
- generatedChecksum: EBC9AD17B5DCF76A8EDA531E3D2ECDA5
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: pm.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: EBC9AD17B5DCF76A8EDA531E3D2ECDA5
- generatedChecksum: 7AED24682E6782ACD411A220C99C4F7A
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: port.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7AED24682E6782ACD411A220C99C4F7A
- generatedChecksum: B838D9B01315613C8EFF25C5BB950F80
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: ptc.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: B838D9B01315613C8EFF25C5BB950F80
- generatedChecksum: 87D1C55E9ECF3BCCB24FA600CBFCC930
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: rtc.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 87D1C55E9ECF3BCCB24FA600CBFCC930
- generatedChecksum: DC4D76B9794A235883D7F5D3FDC6F082
  logicalPath: packs/ATSAMD21G18A_DFP/pio
  name: samd21g18a.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/pio
  security: NON_SECURE
  type: HEADER
  userChecksum: DC4D76B9794A235883D7F5D3FDC6F082
- generatedChecksum: 4253FCE0B35C0AB2AA0253652C488761
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: sercom.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4253FCE0B35C0AB2AA0253652C488761
- generatedChecksum: 0258BE6535CDDE44682CC0CDCB222880
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: sysctrl.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 0258BE6535CDDE44682CC0CDCB222880
- generatedChecksum: E9BCB2B0F7AA6142C2681C1155F88131
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: tc.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: E9BCB2B0F7AA6142C2681C1155F88131
- generatedChecksum: 5819925250D9C7C86B56A48BF0949196
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: tcc.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5819925250D9C7C86B56A48BF0949196
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config/SAMD21_WG_IOT
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: F123D6104DB9C55CD684CE27F3B22781
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: usb.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: F123D6104DB9C55CD684CE27F3B22781
- generatedChecksum: AF14D78B734053187B6E93E19BD70449
  logicalPath: packs/ATSAMD21G18A_DFP/component
  name: wdt.h
  physicalPath: ../../packs/ATSAMD21G18A_DFP/component
  security: NON_SECURE
  type: HEADER
  userChecksum: AF14D78B734053187B6E93E19BD70449
- generatedChecksum: 29AFB0F8B0B358086267A5A68EBEFC01
  logicalPath: config/SAMD21_WG_IOT
  name: ATSAMD21G18A.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 29AFB0F8B0B358086267A5A68EBEFC01
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/SAMD21_WG_IOT;../src/packs/ATSAMD21G18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/SAMD21_WG_IOT;../src/packs/ATSAMD21G18A_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
